### ISSUE TITLE
Tax4Fun2 Functional Prediction Error

### ISSUE THREAD

**Issue by vaughnsteph14** [songweizhi/Tax4Fun2_short_tutorial#1]
I am attempting to run through the short tutorial for making functional predictions using the default database. I am able to run through the majority of the code suggested here. However, I receive the following error when running the "makeFunctionalPrediction" function: 

"Using minimum idenity cutoff of 99% to nearest neighbor
Error in h(simpleError(msg, call)) : 
  error in evaluating the argument 'x' in selecting a method for function 'aggregate': incorrect number of dimensions."
  
Both my ASV abundance table and fasta file contain 2,997 ASVs.
  Here is a link to my ASV abundance file:
[tax4fun_ASVs_cray.csv](https://github.com/songweizhi/Tax4Fun2_short_tutorial/files/14091543/tax4fun_ASVs_cray.csv)

Thank you for the help!
Stephanie

**Comment by pratyusha73** [comment]
I'm facing the same issue. Any help would be appreciated.

**Comment by cathypfister** [comment]
I too have the same error and do not see anyone addressing it. Thank you.

**Comment by songweizhi** [comment]
Please refers to #3 for a possible solution.
