### ISSUE TITLE
"Tax4Fun2_ReferenceData_v2/blast_bin/bin/blastn.exe' not found" 

### ISSUE THREAD

**Issue by EsbergA** [songweizhi/Tax4Fun2_short_tutorial#2]
Dear all, 
I running the example files using the example code but I get the same error everytime: 
"Tax4Fun2_ReferenceData_v2/blast_bin/bin/blastn.exe' not found" 

I have extracted the folder and as I see it everything should be in place, any suggestions? 

# modify the following 8 lines as needed
query_otu_seq   = 'demo_OTU.fasta'              # input OTU sequence file
query_otu_table = 'demo_OTU_table.csv'          # input OTU table
pwd_op_folder   = 'C:/Users/anes0001/Documents/Tax4Fun2/out1'      # output directory
pwd_ref_data    = 'C:/Users/anes0001/Documents/Tax4Fun2/Tax4Fun2_ReferenceData_v2'   # path to the default database (i.e., Tax4Fun2_ReferenceData_v2), need to be decompressed before use
norm_by_cn      = TRUE                          # normalize_by_copy_number (TRUE or FALSE)
norm_path       = TRUE                          # normalize_pathways (TRUE or FALSE)
iden            = 0.97                          # min_identity_to_reference, please modify as needed
num_of_threads  = 2                             # number of CPU cores to use, please modify as needed

# predict functions
runRefBlast(path_to_otus = query_otu_seq, 
            path_to_reference_data = pwd_ref_data, 
            path_to_temp_folder = pwd_op_folder, 
            database_mode = "Ref99NR", 
            use_force = T, 
            num_threads = num_of_threads)

makeFunctionalPrediction(path_to_otu_table = query_otu_table, 
                         path_to_reference_data = pwd_ref_data, 
                         path_to_temp_folder = pwd_op_folder, 
                         database_mode = "Ref99NR", 
                         normalize_by_copy_number = norm_by_cn, 
                         min_identity_to_reference = iden, 
                         normalize_pathways = norm_path)

Best regards,
Anders

**Comment by stalin-antony** [comment]
You have to follow this step to solve the issue. (Mostly this problem occurs in the Windows version)

1. If you are using R studio in Windows, try to Install the standalone version of the BLAST (https://ftp.ncbi.nlm.nih.gov/blast/executables/LATEST/)
2. Once you have done the installation, go to the installation directory in Windows, (Example: C:\Program Files\NCBI\blast-2.15.0+\bin)
3. copy all the binary files from the folder, and paste (replace) them into the binary folder of Tax4Fun2_ReferenceData_v2 (Tax4Fun2_ReferenceData_v2\blast_bin\bin).
4. That's it. Now you can run the command. It will work.

good luck....

Dr. Antony Stalin

**Comment by Angelacrislg** [comment]
Hola he intentado de todo y no he podido arreglar el error, saben donde puedo encoentrara un tutorial de Taxa4Fun para guiarme
