### ISSUE TITLE
Tax4Fun2 error in makeFunctionalPredictions()

### ISSUE THREAD

**Issue by JulianMiGoe** [songweizhi/Tax4Fun2_short_tutorial#3]
When running the Taqx4Fun2 makeFunctionalPredictions() command I receive an error. 

Here is the code I am running (I shortened the paths):

>query_otu_seq    = './table_sequences_asvNames_filtered.fasta'     
>query_otu_table  = './table_ASV_filtered.csv'  
>pwd_op_folder    = './Tax4Fun2_output_folder'                         
>pwd_ref_data      = './Tax4Fun2_ReferenceData_v2'                      
>norm_by_cn        = TRUE                  
>norm_path          = TRUE                     
>iden                    = 0.97                          
>num_of_threads  = 6                        

>runRefBlast(path_to_otus = query_otu_seq, path_to_reference_data = pwd_ref_data, path_to_temp_folder = pwd_op_folder, database_mode = "Ref99NR", use_force = T, num_threads = num_of_threads)

>makeFunctionalPrediction(path_to_otu_table = query_otu_table, path_to_reference_data = pwd_ref_data, path_to_temp_folder = pwd_op_folder, database_mode = "Ref99NR", normalize_by_copy_number = norm_by_cn, min_identity_to_reference = iden, normalize_pathways = norm_path)

I receive the following error message:

>Error in otu_table_reduced[, -1] : incorrect number of dimensions

I ran the code on the demo OTU tables and everything worked. When using my data I only get to create the ref_blast but I cannot make the functional predictions. Both my seq and otu tables have the same lenght (amount of ASVs), they are in the first coloumn in both tables as well. The OTU table does not include any other information asides from ASVs and counts per sample. 

I hope that someone can help me with this issue, thanks in advance!

Cheers,
Julian

**Comment by rishidash12** [comment]
I encountered a similar error. I adjusted the dimensions of the OTU table to match the reference BLAST file, but the same error persists.

**Comment by Beccy7** [comment]
I encountered the same problem. I realized that my .csv (query_otu_table) file was not saving in the same format as the demo .csv file (not sure why). I saved my "query_otu_table" as a tab delimited text file and the MakeFuncitonalPredictions worked, without giving the "Error in otu_table_reduced[, -1] : incorrect number of dimensions" error. Hope this might help.
