### ISSUE TITLE
Error during run

### ISSUE THREAD

**Issue by christellesawaya** [songweizhi/Tax4Fun2_short_tutorial#5]
Hi, I am trying to run the Tax4FUN2 pipeline on R and get this error after some time:
Warning: cannot open file '/Users/..../Tax4FUN2/Tax4Fun2_ReferenceData_v2/KEGG/ko.txt': No such file or directoryError in file(file, "rt") : cannot open the connection

Could you please help me with this issue?

Thank you,
Christelle

**Comment by songweizhi** [comment]
Hi Christelle,

Have you downloaded the referende dataser Tax4Fun2_ReferenceData_v2 on your computer and provided the corrected path to this folder?

Weizhi

**Comment by christellesawaya** [comment]
I downloaded it again and rerun the code.
Are output files correct? (image attached)
<img width="244" alt="Screenshot 2024-08-20 at 7 26 08 PM" src="https://github.com/user-attachments/assets/4787cbef-a89c-4775-ac34-ce214364409d">

Thank you!
Christelle

**Comment by songweizhi** [comment]
Looks good to me (by their names), there are also some example input/output files included in this repo: https://github.com/songweizhi/Tax4Fun2_short_tutorial/blob/master/example_input_files/outputs.zip

**Comment by christellesawaya** [comment]
Thank you for validating, the content is correct (I was using the tutorial files as well).
I am trying now to run it with my actual data I obtained from mothur SOP. 
For .fasta, i am using a representative sequences .fasta file.
I am not sure what _table.txt file to use, I have a .shared file that contains counts , and it caused the following error: 
"Using minimum idenity cutoff of 97% to nearest neighbor
Error in read.table(file = file, header = header, sep = sep, quote = quote,  : 
  more columns than column names"

**Comment by songweizhi** [comment]
the table file contains the abundance information of OTUs across your samples.
